# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_point',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tech_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_case',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_markets',
            field=models.ManyToManyField(blank=True, to='products.TargetMarket'),
        ),
    ]
